// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookapp.Data;

#nullable disable

namespace BookApp.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20230607124824_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("bookapp.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("AuthorId");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("Index_FullName");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            FirstName = "WyoTech",
                            LastName = ""
                        },
                        new
                        {
                            AuthorId = 2,
                            FirstName = " I-CAR",
                            LastName = ""
                        },
                        new
                        {
                            AuthorId = 3,
                            FirstName = "Solutions & Solutions",
                            LastName = ""
                        },
                        new
                        {
                            AuthorId = 4,
                            FirstName = "Doug ",
                            LastName = "Larue"
                        },
                        new
                        {
                            AuthorId = 5,
                            FirstName = "Randy ",
                            LastName = "Svalina"
                        },
                        new
                        {
                            AuthorId = 6,
                            FirstName = "Gary ",
                            LastName = "Puls"
                        },
                        new
                        {
                            AuthorId = 7,
                            FirstName = "Andrew",
                            LastName = "A."
                        },
                        new
                        {
                            AuthorId = 8,
                            FirstName = "Rezin",
                            LastName = "Ph.D"
                        },
                        new
                        {
                            AuthorId = 9,
                            FirstName = "Jack",
                            LastName = "Erjavec"
                        },
                        new
                        {
                            AuthorId = 10,
                            FirstName = "Rob",
                            LastName = "Thompson"
                        });
                });

            modelBuilder.Entity("bookapp.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ISBN")
                        .HasColumnType("varchar(255)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PublishedOn")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("BookId");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasDatabaseName("Unique_ISBN_Index");

                    b.HasIndex("Title")
                        .HasDatabaseName("Index_BookTitle");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Description = "Collision Repair I",
                            ISBN = "978-1-323-00001-1",
                            Price = 75f,
                            PublishedOn = 2022,
                            Publisher = "Modern Printing",
                            Title = "Collision Repair I"
                        },
                        new
                        {
                            BookId = 2,
                            Description = "Collision Repair II",
                            ISBN = "978-1-323-00002-1",
                            Price = 60f,
                            PublishedOn = 2020,
                            Publisher = "Modern Printing",
                            Title = "Collision Repair II"
                        },
                        new
                        {
                            BookId = 3,
                            Description = "Refinishing I",
                            ISBN = "978-1-323-00003-1",
                            Price = 50f,
                            PublishedOn = 2022,
                            Publisher = "Modern Printing",
                            Title = "Refinishing I"
                        },
                        new
                        {
                            BookId = 4,
                            Description = "Refinishing II",
                            ISBN = "978-1-323-00004-1",
                            Price = 80f,
                            PublishedOn = 2020,
                            Publisher = "Modern Printing",
                            Title = "Refinishing II"
                        },
                        new
                        {
                            BookId = 5,
                            Description = "Motorsports Chassis Frabrication I",
                            ISBN = "978-1-323-39626-1",
                            Price = 69.4f,
                            PublishedOn = 2020,
                            Publisher = "Pearson Publishing",
                            Title = "Motorsports Chassis Frabrication I"
                        },
                        new
                        {
                            BookId = 6,
                            Description = "Motorsports Chassis Fabrication II",
                            ISBN = "978-1-323-39627-8",
                            Price = 76.4f,
                            PublishedOn = 2020,
                            Publisher = "Pearson Publishing",
                            Title = "Motorsports Chassis Fabrication II"
                        },
                        new
                        {
                            BookId = 7,
                            Description = "Basic Street Rod",
                            ISBN = "978-1-323-00005-1",
                            Price = 136.15f,
                            PublishedOn = 2021,
                            Publisher = "Kinkos",
                            Title = "Basic Street Rod"
                        },
                        new
                        {
                            BookId = 8,
                            Description = "Advanced Street Rod",
                            ISBN = "978-1-323-00006-1",
                            Price = 73.05f,
                            PublishedOn = 2022,
                            Publisher = "Kinkos",
                            Title = "Advanced Street Rod"
                        },
                        new
                        {
                            BookId = 9,
                            Description = "Custom Paint Book",
                            ISBN = "978-1-323-00007-1",
                            Price = 128.57f,
                            PublishedOn = 2020,
                            Publisher = "Kinkos",
                            Title = "Custom Paint Book"
                        },
                        new
                        {
                            BookId = 10,
                            Description = "Trim and Upholstery I",
                            ISBN = "978-1-323-00008-1",
                            Price = 156.5f,
                            PublishedOn = 2021,
                            Publisher = "Custom Print",
                            Title = "Trim and Upholstery I"
                        },
                        new
                        {
                            BookId = 11,
                            Description = "Trim and Upholstery II",
                            ISBN = "978-1-323-00009-1",
                            Price = 108.09f,
                            PublishedOn = 2021,
                            Publisher = "Custom Print",
                            Title = "Trim and Upholstery II"
                        },
                        new
                        {
                            BookId = 12,
                            Description = "Accounting and Financial Management",
                            ISBN = "978-0-134-70985-1",
                            Price = 166.65f,
                            PublishedOn = 2020,
                            Publisher = "Prentice Hall",
                            Title = "Accounting and Financial Management"
                        },
                        new
                        {
                            BookId = 13,
                            Description = "Computers and Business Applications",
                            ISBN = "978-0-134-70985-2",
                            Price = 166.65f,
                            PublishedOn = 2021,
                            Publisher = "Prentice Hall",
                            Title = "Computers and Business Applications"
                        },
                        new
                        {
                            BookId = 14,
                            Description = "Communications",
                            ISBN = "978-0-134-70985-3",
                            Price = 166.65f,
                            PublishedOn = 2021,
                            Publisher = "Prentice Hall",
                            Title = "Communications"
                        },
                        new
                        {
                            BookId = 15,
                            Description = "Management Concepts",
                            ISBN = "978-0-134-70985-4",
                            Price = 166.65f,
                            PublishedOn = 2020,
                            Publisher = "Prentice Hall",
                            Title = "Management Concepts"
                        },
                        new
                        {
                            BookId = 16,
                            Description = "Human Resources Management",
                            ISBN = "978-0-134-70985-5",
                            Price = 166.65f,
                            PublishedOn = 2021,
                            Publisher = "Prentice Hall",
                            Title = "Human Resources Management"
                        },
                        new
                        {
                            BookId = 17,
                            Description = "Shop Management",
                            ISBN = "978-0-134-70985-6",
                            Price = 166.65f,
                            PublishedOn = 2021,
                            Publisher = "Prentice Hall",
                            Title = "Shop Management"
                        },
                        new
                        {
                            BookId = 18,
                            Description = "Basic Engine Management Systems",
                            ISBN = "978-1-133-61231-5",
                            Price = 149.95f,
                            PublishedOn = 2020,
                            Publisher = "Cengage Learning",
                            Title = "Basic Engine Management Systems"
                        },
                        new
                        {
                            BookId = 19,
                            Description = "Drivability Diagnostics",
                            ISBN = "978-1-133-61231-6",
                            Price = 149.95f,
                            PublishedOn = 2022,
                            Publisher = "Cengage Learning",
                            Title = "Drivability Diagnostics"
                        },
                        new
                        {
                            BookId = 20,
                            Description = "Drivetrain Systems",
                            ISBN = "978-1-133-61231-7",
                            Price = 149.95f,
                            PublishedOn = 2020,
                            Publisher = "Cengage Learning",
                            Title = "Drivetrain Systems"
                        });
                });

            modelBuilder.Entity("bookapp.Models.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthor");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            Order = 1
                        },
                        new
                        {
                            BookId = 1,
                            AuthorId = 2,
                            Order = 2
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1,
                            Order = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2,
                            Order = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 1,
                            Order = 1
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2,
                            Order = 2
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1,
                            Order = 1
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 2,
                            Order = 2
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 3,
                            Order = 1
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 3,
                            Order = 1
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 4,
                            Order = 1
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 5,
                            Order = 2
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 4,
                            Order = 1
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 5,
                            Order = 2
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 6,
                            Order = 1
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 1,
                            Order = 1
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 1,
                            Order = 1
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 7,
                            Order = 1
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 8,
                            Order = 2
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 7,
                            Order = 1
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 8,
                            Order = 2
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 7,
                            Order = 1
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 8,
                            Order = 2
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 7,
                            Order = 1
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 8,
                            Order = 2
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 7,
                            Order = 1
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 8,
                            Order = 2
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 7,
                            Order = 1
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 8,
                            Order = 2
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 9,
                            Order = 1
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 10,
                            Order = 2
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 9,
                            Order = 1
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 10,
                            Order = 2
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 9,
                            Order = 1
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 10,
                            Order = 2
                        });
                });

            modelBuilder.Entity("bookapp.Models.PriceOffer", b =>
                {
                    b.Property<int>("PriceOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<float>("NewPrice")
                        .HasColumnType("float");

                    b.Property<string>("OfferText")
                        .HasColumnType("longtext");

                    b.HasKey("PriceOfferId");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("PriceOffer");

                    b.HasData(
                        new
                        {
                            PriceOfferId = 1,
                            BookId = 1,
                            NewPrice = 26.25f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 2,
                            BookId = 2,
                            NewPrice = 30f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 3,
                            BookId = 3,
                            NewPrice = 25.25f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 4,
                            BookId = 4,
                            NewPrice = 30f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 5,
                            BookId = 5,
                            NewPrice = 24.29f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 6,
                            BookId = 6,
                            NewPrice = 20.06f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 7,
                            BookId = 7,
                            NewPrice = 47.65f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 8,
                            BookId = 8,
                            NewPrice = 25.57f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 9,
                            BookId = 9,
                            NewPrice = 45f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 10,
                            BookId = 10,
                            NewPrice = 54.78f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 11,
                            BookId = 11,
                            NewPrice = 37.83f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 12,
                            BookId = 12,
                            NewPrice = 58.33f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 13,
                            BookId = 13,
                            NewPrice = 58.33f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 14,
                            BookId = 14,
                            NewPrice = 58.33f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 15,
                            BookId = 15,
                            NewPrice = 58.33f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 16,
                            BookId = 16,
                            NewPrice = 58.33f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 17,
                            BookId = 17,
                            NewPrice = 58.33f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 18,
                            BookId = 18,
                            NewPrice = 52.48f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 19,
                            BookId = 19,
                            NewPrice = 52.48f,
                            OfferText = ""
                        },
                        new
                        {
                            PriceOfferId = 20,
                            BookId = 20,
                            NewPrice = 52.48f,
                            OfferText = ""
                        });
                });

            modelBuilder.Entity("bookapp.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("VoterName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookId");

                    b.HasIndex("VoterName")
                        .HasDatabaseName("Index_VoterName");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            BookId = 3,
                            Comment = "Not bad",
                            Rating = 6,
                            VoterName = "Abdellah"
                        },
                        new
                        {
                            ReviewId = 2,
                            BookId = 18,
                            Comment = "Not bad",
                            Rating = 6,
                            VoterName = "Abdellah"
                        },
                        new
                        {
                            ReviewId = 3,
                            BookId = 19,
                            Comment = "bad",
                            Rating = 3,
                            VoterName = "Abdellah"
                        },
                        new
                        {
                            ReviewId = 4,
                            BookId = 20,
                            Comment = "bad",
                            Rating = 3,
                            VoterName = "Abdellah"
                        },
                        new
                        {
                            ReviewId = 5,
                            BookId = 2,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Ali"
                        },
                        new
                        {
                            ReviewId = 6,
                            BookId = 17,
                            Comment = "bad",
                            Rating = 4,
                            VoterName = "Ali"
                        },
                        new
                        {
                            ReviewId = 7,
                            BookId = 18,
                            Comment = "bad",
                            Rating = 4,
                            VoterName = "Ali"
                        },
                        new
                        {
                            ReviewId = 8,
                            BookId = 19,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Ali"
                        },
                        new
                        {
                            ReviewId = 9,
                            BookId = 8,
                            Comment = "average",
                            Rating = 6,
                            VoterName = "Halima"
                        },
                        new
                        {
                            ReviewId = 10,
                            BookId = 13,
                            Comment = "average",
                            Rating = 6,
                            VoterName = "Halima"
                        },
                        new
                        {
                            ReviewId = 11,
                            BookId = 15,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Halima"
                        },
                        new
                        {
                            ReviewId = 12,
                            BookId = 3,
                            Comment = "",
                            Rating = 5,
                            VoterName = "Kamal"
                        },
                        new
                        {
                            ReviewId = 13,
                            BookId = 4,
                            Comment = "",
                            Rating = 5,
                            VoterName = "Kamal"
                        },
                        new
                        {
                            ReviewId = 14,
                            BookId = 5,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Kamal"
                        },
                        new
                        {
                            ReviewId = 15,
                            BookId = 6,
                            Comment = "bad",
                            Rating = 3,
                            VoterName = "Kamal"
                        },
                        new
                        {
                            ReviewId = 16,
                            BookId = 10,
                            Comment = "",
                            Rating = 5,
                            VoterName = "Kamal"
                        },
                        new
                        {
                            ReviewId = 17,
                            BookId = 11,
                            Comment = "",
                            Rating = 5,
                            VoterName = "Kamal"
                        },
                        new
                        {
                            ReviewId = 18,
                            BookId = 15,
                            Comment = "bad",
                            Rating = 3,
                            VoterName = "Kamal"
                        },
                        new
                        {
                            ReviewId = 19,
                            BookId = 16,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Kamal"
                        },
                        new
                        {
                            ReviewId = 20,
                            BookId = 1,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Karim"
                        },
                        new
                        {
                            ReviewId = 21,
                            BookId = 6,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Karim"
                        },
                        new
                        {
                            ReviewId = 22,
                            BookId = 9,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Karim"
                        },
                        new
                        {
                            ReviewId = 23,
                            BookId = 20,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Karim"
                        },
                        new
                        {
                            ReviewId = 24,
                            BookId = 7,
                            Comment = "",
                            Rating = 8,
                            VoterName = "Laila"
                        },
                        new
                        {
                            ReviewId = 25,
                            BookId = 13,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Laila"
                        },
                        new
                        {
                            ReviewId = 26,
                            BookId = 14,
                            Comment = "",
                            Rating = 8,
                            VoterName = "Laila"
                        },
                        new
                        {
                            ReviewId = 27,
                            BookId = 16,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Laila"
                        },
                        new
                        {
                            ReviewId = 28,
                            BookId = 1,
                            Comment = "Nice  Book",
                            Rating = 9,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 29,
                            BookId = 2,
                            Comment = "average",
                            Rating = 6,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 30,
                            BookId = 4,
                            Comment = "",
                            Rating = 5,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 31,
                            BookId = 5,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 32,
                            BookId = 7,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 33,
                            BookId = 10,
                            Comment = "average",
                            Rating = 7,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 34,
                            BookId = 11,
                            Comment = "bad",
                            Rating = 4,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 35,
                            BookId = 12,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 36,
                            BookId = 14,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 37,
                            BookId = 17,
                            Comment = "",
                            Rating = 5,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 38,
                            BookId = 19,
                            Comment = "Not bad",
                            Rating = 6,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 39,
                            BookId = 20,
                            Comment = "Nice  Book",
                            Rating = 9,
                            VoterName = "Mohamed"
                        },
                        new
                        {
                            ReviewId = 40,
                            BookId = 2,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Patrice"
                        },
                        new
                        {
                            ReviewId = 41,
                            BookId = 3,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Patrice"
                        },
                        new
                        {
                            ReviewId = 42,
                            BookId = 7,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Patrice"
                        },
                        new
                        {
                            ReviewId = 43,
                            BookId = 12,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Patrice"
                        },
                        new
                        {
                            ReviewId = 44,
                            BookId = 17,
                            Comment = "average",
                            Rating = 7,
                            VoterName = "Patrice"
                        },
                        new
                        {
                            ReviewId = 45,
                            BookId = 18,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Patrice"
                        },
                        new
                        {
                            ReviewId = 46,
                            BookId = 19,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Patrice"
                        },
                        new
                        {
                            ReviewId = 47,
                            BookId = 9,
                            Comment = "",
                            Rating = 5,
                            VoterName = "Sabiri"
                        },
                        new
                        {
                            ReviewId = 48,
                            BookId = 11,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Sabiri"
                        },
                        new
                        {
                            ReviewId = 49,
                            BookId = 12,
                            Comment = "",
                            Rating = 5,
                            VoterName = "Sabiri"
                        },
                        new
                        {
                            ReviewId = 50,
                            BookId = 16,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Sabiri"
                        },
                        new
                        {
                            ReviewId = 51,
                            BookId = 4,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Slimani"
                        },
                        new
                        {
                            ReviewId = 52,
                            BookId = 7,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Slimani"
                        },
                        new
                        {
                            ReviewId = 53,
                            BookId = 8,
                            Comment = "",
                            Rating = 8,
                            VoterName = "Slimani"
                        },
                        new
                        {
                            ReviewId = 54,
                            BookId = 9,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Slimani"
                        },
                        new
                        {
                            ReviewId = 55,
                            BookId = 10,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Slimani"
                        },
                        new
                        {
                            ReviewId = 56,
                            BookId = 13,
                            Comment = "",
                            Rating = 8,
                            VoterName = "Slimani"
                        },
                        new
                        {
                            ReviewId = 57,
                            BookId = 14,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Slimani"
                        },
                        new
                        {
                            ReviewId = 58,
                            BookId = 17,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Slimani"
                        },
                        new
                        {
                            ReviewId = 59,
                            BookId = 8,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Yassine"
                        },
                        new
                        {
                            ReviewId = 60,
                            BookId = 13,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Yassine"
                        },
                        new
                        {
                            ReviewId = 61,
                            BookId = 14,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Yassine"
                        },
                        new
                        {
                            ReviewId = 62,
                            BookId = 15,
                            Comment = "good",
                            Rating = 8,
                            VoterName = "Yassine"
                        },
                        new
                        {
                            ReviewId = 63,
                            BookId = 3,
                            Comment = "Nice  Book",
                            Rating = 9,
                            VoterName = "Zineb"
                        },
                        new
                        {
                            ReviewId = 64,
                            BookId = 4,
                            Comment = "good",
                            Rating = 9,
                            VoterName = "Zineb"
                        },
                        new
                        {
                            ReviewId = 65,
                            BookId = 5,
                            Comment = "Nice  Book",
                            Rating = 9,
                            VoterName = "Zineb"
                        },
                        new
                        {
                            ReviewId = 66,
                            BookId = 6,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Zineb"
                        },
                        new
                        {
                            ReviewId = 67,
                            BookId = 15,
                            Comment = "average",
                            Rating = 5,
                            VoterName = "Zineb"
                        },
                        new
                        {
                            ReviewId = 68,
                            BookId = 16,
                            Comment = "good",
                            Rating = 10,
                            VoterName = "Zineb"
                        },
                        new
                        {
                            ReviewId = 69,
                            BookId = 1,
                            Comment = "good",
                            Rating = 10,
                            VoterName = "Ziyad"
                        },
                        new
                        {
                            ReviewId = 70,
                            BookId = 2,
                            Comment = "good",
                            Rating = 10,
                            VoterName = "Ziyad"
                        },
                        new
                        {
                            ReviewId = 71,
                            BookId = 9,
                            Comment = "good",
                            Rating = 9,
                            VoterName = "Ziyad"
                        },
                        new
                        {
                            ReviewId = 72,
                            BookId = 12,
                            Comment = "good",
                            Rating = 9,
                            VoterName = "Ziyad"
                        });
                });

            modelBuilder.Entity("bookapp.Models.BookAuthor", b =>
                {
                    b.HasOne("bookapp.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bookapp.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("bookapp.Models.PriceOffer", b =>
                {
                    b.HasOne("bookapp.Models.Book", "Book")
                        .WithOne("PriceOffer")
                        .HasForeignKey("bookapp.Models.PriceOffer", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("bookapp.Models.Review", b =>
                {
                    b.HasOne("bookapp.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("bookapp.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("bookapp.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("PriceOffer");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
